import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/globals.css";
import Footer from "@/components/ui/Footer";
import Navbar from "@/components/ui/Navbar";

const font = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
